fix: Add wait for ECS to become avaliable

diff --git a/.github/workflows/deploy-db.yml b/.github/workflows/deploy-db.yml
--- a/.github/workflows/deploy-db.yml
+++ b/.github/workflows/deploy-db.yml
@@ -143,13 +143,33 @@ jobs:
           --service-name $service_name \
           --query 'taskArns[0]' --output text)
         
-        # Connect directly to the mongosh to setup the replica set
-        aws ecs execute-command \
-          --cluster "$cluster_name" \
-          --task "$task_arn" \
-          --container "mongo" \
-          --interactive \
-          --command "mongosh --quiet --eval \"$MONGO_INIT_SCRIPT\""
+        for i in $(seq 1 10); do
+          echo "Trying to connect to MongoDB cluster instances (Attempt $i/10)..."
+          
+          # Connect directly to the mongosh to setup the replica set
+          aws ecs execute-command \
+            --cluster "$cluster_name" \
+            --task "$task_arn" \
+            --container "mongo" \
+            --interactive \
+            --command "mongosh --quiet --eval \"$MONGO_INIT_SCRIPT\""
+          
+          EXIT_CODE=$?
+          
+          if [ $EXIT_CODE -eq 0 ]; then
+            echo "Replica set established successfully"
+            success=1
+            break
+          fi
+          
+          echo "Connection failed or container not ready. Retrying in 10 seconds..."
+          sleep 10
+        done
+        
+        if [ $success -ne 1 ]; then
+          echo "Failed to reach cluster in 10 tries with ECS command, exiting"
+          exit 1
+        fi
         
     - name: Install Dependencies
       working-directory: ${{ env.CONFIG_DIRECTORY }}
